services:
  db:
    image: mysql:8
    env_file: ../.env
    environment:
      MYSQL_DATABASE: adsb
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    depends_on:
      - db
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5000:5000"

  integrador:
    build:
      context: ../integrador
      dockerfile: Dockerfile
    env_file: ../.env
    depends_on:
      - db
    command: ["python", "-u", "/opt/app/main.py"]
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OPENSKY_CLIENT_ID: ${OPENSKY_CLIENT_ID}
      OPENSKY_CLIENT_SECRET: ${OPENSKY_CLIENT_SECRET}

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"          # expón el puerto que quieras
    depends_on:
      - backend
 
volumes:
  db_data:
