"""initial schema

Revision ID: ceac2a4b7bf1
Revises: 
Create Date: 2025-06-17 15:27:51.907888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceac2a4b7bf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('icao24', sa.String(length=6), nullable=False),
    sa.Column('callsign', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('vel', sa.Integer(), nullable=True),
    sa.Column('is_state', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('icao24')
    )
    op.create_table('vuelos_diplomaticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao24', sa.String(length=6), nullable=True),
    sa.Column('autorizacion', sa.String(length=20), nullable=False),
    sa.Column('validez_desde', sa.DateTime(), nullable=False),
    sa.Column('validez_hasta', sa.DateTime(), nullable=False),
    sa.Column('casilla18', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['icao24'], ['aeronaves.icao24'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vuelos_diplomaticos')
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
